// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.10.0
// source: interface.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmitIssue_Severity int32

const (
	EmitIssue_ERROR   EmitIssue_Severity = 0
	EmitIssue_WARNING EmitIssue_Severity = 1
	EmitIssue_NOTICE  EmitIssue_Severity = 2
)

// Enum value maps for EmitIssue_Severity.
var (
	EmitIssue_Severity_name = map[int32]string{
		0: "ERROR",
		1: "WARNING",
		2: "NOTICE",
	}
	EmitIssue_Severity_value = map[string]int32{
		"ERROR":   0,
		"WARNING": 1,
		"NOTICE":  2,
	}
)

func (x EmitIssue_Severity) Enum() *EmitIssue_Severity {
	p := new(EmitIssue_Severity)
	*p = x
	return p
}

func (x EmitIssue_Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EmitIssue_Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_interface_proto_enumTypes[0].Descriptor()
}

func (EmitIssue_Severity) Type() protoreflect.EnumType {
	return &file_interface_proto_enumTypes[0]
}

func (x EmitIssue_Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EmitIssue_Severity.Descriptor instead.
func (EmitIssue_Severity) EnumDescriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{12, 0}
}

type RuleSetName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RuleSetName) Reset() {
	*x = RuleSetName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleSetName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSetName) ProtoMessage() {}

func (x *RuleSetName) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSetName.ProtoReflect.Descriptor instead.
func (*RuleSetName) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{0}
}

type RuleSetVersion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RuleSetVersion) Reset() {
	*x = RuleSetVersion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleSetVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSetVersion) ProtoMessage() {}

func (x *RuleSetVersion) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSetVersion.ProtoReflect.Descriptor instead.
func (*RuleSetVersion) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{1}
}

type RuleNames struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RuleNames) Reset() {
	*x = RuleNames{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleNames) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleNames) ProtoMessage() {}

func (x *RuleNames) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleNames.ProtoReflect.Descriptor instead.
func (*RuleNames) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{2}
}

type ConfigSchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfigSchema) Reset() {
	*x = ConfigSchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchema) ProtoMessage() {}

func (x *ConfigSchema) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchema.ProtoReflect.Descriptor instead.
func (*ConfigSchema) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{3}
}

type ApplyConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ApplyConfig) Reset() {
	*x = ApplyConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfig) ProtoMessage() {}

func (x *ApplyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyConfig.ProtoReflect.Descriptor instead.
func (*ApplyConfig) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{4}
}

type Check struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Check) Reset() {
	*x = Check{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Check) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check) ProtoMessage() {}

func (x *Check) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check.ProtoReflect.Descriptor instead.
func (*Check) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{5}
}

type BodySchema struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attributes []*BodySchema_Attribute `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	Blocks     []*BodySchema_Block     `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
}

func (x *BodySchema) Reset() {
	*x = BodySchema{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BodySchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodySchema) ProtoMessage() {}

func (x *BodySchema) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodySchema.ProtoReflect.Descriptor instead.
func (*BodySchema) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{6}
}

func (x *BodySchema) GetAttributes() []*BodySchema_Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *BodySchema) GetBlocks() []*BodySchema_Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type BodyContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Attributes       map[string]*BodyContent_Attribute `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Blocks           []*BodyContent_Block              `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	MissingItemRange *Range                            `protobuf:"bytes,3,opt,name=missing_item_range,json=missingItemRange,proto3" json:"missing_item_range,omitempty"`
}

func (x *BodyContent) Reset() {
	*x = BodyContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BodyContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyContent) ProtoMessage() {}

func (x *BodyContent) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyContent.ProtoReflect.Descriptor instead.
func (*BodyContent) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{7}
}

func (x *BodyContent) GetAttributes() map[string]*BodyContent_Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *BodyContent) GetBlocks() []*BodyContent_Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *BodyContent) GetMissingItemRange() *Range {
	if x != nil {
		return x.MissingItemRange
	}
	return nil
}

type Range struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filename string     `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Start    *Range_Pos `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End      *Range_Pos `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
}

func (x *Range) Reset() {
	*x = Range{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range) ProtoMessage() {}

func (x *Range) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range.ProtoReflect.Descriptor instead.
func (*Range) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{8}
}

func (x *Range) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Range) GetStart() *Range_Pos {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *Range) GetEnd() *Range_Pos {
	if x != nil {
		return x.End
	}
	return nil
}

type ResourceContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResourceContent) Reset() {
	*x = ResourceContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceContent) ProtoMessage() {}

func (x *ResourceContent) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceContent.ProtoReflect.Descriptor instead.
func (*ResourceContent) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{9}
}

type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{10}
}

type EvaluateExpr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EvaluateExpr) Reset() {
	*x = EvaluateExpr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluateExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateExpr) ProtoMessage() {}

func (x *EvaluateExpr) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateExpr.ProtoReflect.Descriptor instead.
func (*EvaluateExpr) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{11}
}

type EmitIssue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmitIssue) Reset() {
	*x = EmitIssue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmitIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitIssue) ProtoMessage() {}

func (x *EmitIssue) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitIssue.ProtoReflect.Descriptor instead.
func (*EmitIssue) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{12}
}

type RuleSetName_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RuleSetName_Request) Reset() {
	*x = RuleSetName_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleSetName_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSetName_Request) ProtoMessage() {}

func (x *RuleSetName_Request) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSetName_Request.ProtoReflect.Descriptor instead.
func (*RuleSetName_Request) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{0, 0}
}

type RuleSetName_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RuleSetName_Response) Reset() {
	*x = RuleSetName_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleSetName_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSetName_Response) ProtoMessage() {}

func (x *RuleSetName_Response) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSetName_Response.ProtoReflect.Descriptor instead.
func (*RuleSetName_Response) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{0, 1}
}

func (x *RuleSetName_Response) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RuleSetVersion_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RuleSetVersion_Request) Reset() {
	*x = RuleSetVersion_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleSetVersion_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSetVersion_Request) ProtoMessage() {}

func (x *RuleSetVersion_Request) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSetVersion_Request.ProtoReflect.Descriptor instead.
func (*RuleSetVersion_Request) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{1, 0}
}

type RuleSetVersion_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *RuleSetVersion_Response) Reset() {
	*x = RuleSetVersion_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleSetVersion_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleSetVersion_Response) ProtoMessage() {}

func (x *RuleSetVersion_Response) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleSetVersion_Response.ProtoReflect.Descriptor instead.
func (*RuleSetVersion_Response) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{1, 1}
}

func (x *RuleSetVersion_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RuleNames_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RuleNames_Request) Reset() {
	*x = RuleNames_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleNames_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleNames_Request) ProtoMessage() {}

func (x *RuleNames_Request) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleNames_Request.ProtoReflect.Descriptor instead.
func (*RuleNames_Request) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{2, 0}
}

type RuleNames_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Names []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
}

func (x *RuleNames_Response) Reset() {
	*x = RuleNames_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuleNames_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleNames_Response) ProtoMessage() {}

func (x *RuleNames_Response) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleNames_Response.ProtoReflect.Descriptor instead.
func (*RuleNames_Response) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{2, 1}
}

func (x *RuleNames_Response) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type ConfigSchema_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ConfigSchema_Request) Reset() {
	*x = ConfigSchema_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigSchema_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchema_Request) ProtoMessage() {}

func (x *ConfigSchema_Request) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchema_Request.ProtoReflect.Descriptor instead.
func (*ConfigSchema_Request) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{3, 0}
}

type ConfigSchema_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body *BodySchema `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *ConfigSchema_Response) Reset() {
	*x = ConfigSchema_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfigSchema_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSchema_Response) ProtoMessage() {}

func (x *ConfigSchema_Response) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSchema_Response.ProtoReflect.Descriptor instead.
func (*ConfigSchema_Response) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ConfigSchema_Response) GetBody() *BodySchema {
	if x != nil {
		return x.Body
	}
	return nil
}

type ApplyConfig_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body *BodyContent `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *ApplyConfig_Request) Reset() {
	*x = ApplyConfig_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfig_Request) ProtoMessage() {}

func (x *ApplyConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyConfig_Request.ProtoReflect.Descriptor instead.
func (*ApplyConfig_Request) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ApplyConfig_Request) GetBody() *BodyContent {
	if x != nil {
		return x.Body
	}
	return nil
}

type ApplyConfig_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ApplyConfig_Response) Reset() {
	*x = ApplyConfig_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplyConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyConfig_Response) ProtoMessage() {}

func (x *ApplyConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyConfig_Response.ProtoReflect.Descriptor instead.
func (*ApplyConfig_Response) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{4, 1}
}

type Check_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Runner uint32 `protobuf:"varint,1,opt,name=runner,proto3" json:"runner,omitempty"`
}

func (x *Check_Request) Reset() {
	*x = Check_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Check_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check_Request) ProtoMessage() {}

func (x *Check_Request) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check_Request.ProtoReflect.Descriptor instead.
func (*Check_Request) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Check_Request) GetRunner() uint32 {
	if x != nil {
		return x.Runner
	}
	return 0
}

type Check_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Check_Response) Reset() {
	*x = Check_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Check_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Check_Response) ProtoMessage() {}

func (x *Check_Response) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Check_Response.ProtoReflect.Descriptor instead.
func (*Check_Response) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{5, 1}
}

type BodySchema_Attribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *BodySchema_Attribute) Reset() {
	*x = BodySchema_Attribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BodySchema_Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodySchema_Attribute) ProtoMessage() {}

func (x *BodySchema_Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodySchema_Attribute.ProtoReflect.Descriptor instead.
func (*BodySchema_Attribute) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{6, 0}
}

func (x *BodySchema_Attribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type BodySchema_Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       string      `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	LabelNames []string    `protobuf:"bytes,2,rep,name=label_names,json=labelNames,proto3" json:"label_names,omitempty"`
	Body       *BodySchema `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *BodySchema_Block) Reset() {
	*x = BodySchema_Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BodySchema_Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodySchema_Block) ProtoMessage() {}

func (x *BodySchema_Block) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodySchema_Block.ProtoReflect.Descriptor instead.
func (*BodySchema_Block) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{6, 1}
}

func (x *BodySchema_Block) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BodySchema_Block) GetLabelNames() []string {
	if x != nil {
		return x.LabelNames
	}
	return nil
}

func (x *BodySchema_Block) GetBody() *BodySchema {
	if x != nil {
		return x.Body
	}
	return nil
}

type BodyContent_Attribute struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Expr      []byte `protobuf:"bytes,2,opt,name=expr,proto3" json:"expr,omitempty"`
	Range     *Range `protobuf:"bytes,3,opt,name=range,proto3" json:"range,omitempty"`
	NameRange *Range `protobuf:"bytes,4,opt,name=name_range,json=nameRange,proto3" json:"name_range,omitempty"`
	ExprRange *Range `protobuf:"bytes,5,opt,name=expr_range,json=exprRange,proto3" json:"expr_range,omitempty"`
}

func (x *BodyContent_Attribute) Reset() {
	*x = BodyContent_Attribute{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BodyContent_Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyContent_Attribute) ProtoMessage() {}

func (x *BodyContent_Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyContent_Attribute.ProtoReflect.Descriptor instead.
func (*BodyContent_Attribute) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{7, 0}
}

func (x *BodyContent_Attribute) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BodyContent_Attribute) GetExpr() []byte {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *BodyContent_Attribute) GetRange() *Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *BodyContent_Attribute) GetNameRange() *Range {
	if x != nil {
		return x.NameRange
	}
	return nil
}

func (x *BodyContent_Attribute) GetExprRange() *Range {
	if x != nil {
		return x.ExprRange
	}
	return nil
}

type BodyContent_Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type        string       `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Labels      []string     `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
	Body        *BodyContent `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	DefRange    *Range       `protobuf:"bytes,4,opt,name=def_range,json=defRange,proto3" json:"def_range,omitempty"`
	TypeRange   *Range       `protobuf:"bytes,5,opt,name=type_range,json=typeRange,proto3" json:"type_range,omitempty"`
	LabelRanges []*Range     `protobuf:"bytes,6,rep,name=label_ranges,json=labelRanges,proto3" json:"label_ranges,omitempty"`
}

func (x *BodyContent_Block) Reset() {
	*x = BodyContent_Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BodyContent_Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyContent_Block) ProtoMessage() {}

func (x *BodyContent_Block) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyContent_Block.ProtoReflect.Descriptor instead.
func (*BodyContent_Block) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{7, 1}
}

func (x *BodyContent_Block) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BodyContent_Block) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *BodyContent_Block) GetBody() *BodyContent {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *BodyContent_Block) GetDefRange() *Range {
	if x != nil {
		return x.DefRange
	}
	return nil
}

func (x *BodyContent_Block) GetTypeRange() *Range {
	if x != nil {
		return x.TypeRange
	}
	return nil
}

func (x *BodyContent_Block) GetLabelRanges() []*Range {
	if x != nil {
		return x.LabelRanges
	}
	return nil
}

type Range_Pos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Line   int64 `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	Column int64 `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	Byte   int64 `protobuf:"varint,3,opt,name=byte,proto3" json:"byte,omitempty"`
}

func (x *Range_Pos) Reset() {
	*x = Range_Pos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Range_Pos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Range_Pos) ProtoMessage() {}

func (x *Range_Pos) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Range_Pos.ProtoReflect.Descriptor instead.
func (*Range_Pos) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{8, 0}
}

func (x *Range_Pos) GetLine() int64 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Range_Pos) GetColumn() int64 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *Range_Pos) GetByte() int64 {
	if x != nil {
		return x.Byte
	}
	return 0
}

type ResourceContent_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource string      `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Schema   *BodySchema `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
}

func (x *ResourceContent_Request) Reset() {
	*x = ResourceContent_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceContent_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceContent_Request) ProtoMessage() {}

func (x *ResourceContent_Request) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceContent_Request.ProtoReflect.Descriptor instead.
func (*ResourceContent_Request) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{9, 0}
}

func (x *ResourceContent_Request) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ResourceContent_Request) GetSchema() *BodySchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type ResourceContent_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content *BodyContent `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *ResourceContent_Response) Reset() {
	*x = ResourceContent_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceContent_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceContent_Response) ProtoMessage() {}

func (x *ResourceContent_Response) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceContent_Response.ProtoReflect.Descriptor instead.
func (*ResourceContent_Response) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{9, 1}
}

func (x *ResourceContent_Response) GetContent() *BodyContent {
	if x != nil {
		return x.Content
	}
	return nil
}

type File_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *File_Request) Reset() {
	*x = File_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File_Request) ProtoMessage() {}

func (x *File_Request) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File_Request.ProtoReflect.Descriptor instead.
func (*File_Request) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{10, 0}
}

func (x *File_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type File_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File []byte `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
}

func (x *File_Response) Reset() {
	*x = File_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File_Response) ProtoMessage() {}

func (x *File_Response) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File_Response.ProtoReflect.Descriptor instead.
func (*File_Response) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{10, 1}
}

func (x *File_Response) GetFile() []byte {
	if x != nil {
		return x.File
	}
	return nil
}

type EvaluateExpr_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expr      []byte `protobuf:"bytes,1,opt,name=expr,proto3" json:"expr,omitempty"`
	ExprRange *Range `protobuf:"bytes,2,opt,name=expr_range,json=exprRange,proto3" json:"expr_range,omitempty"`
	Type      []byte `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *EvaluateExpr_Request) Reset() {
	*x = EvaluateExpr_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluateExpr_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateExpr_Request) ProtoMessage() {}

func (x *EvaluateExpr_Request) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateExpr_Request.ProtoReflect.Descriptor instead.
func (*EvaluateExpr_Request) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{11, 0}
}

func (x *EvaluateExpr_Request) GetExpr() []byte {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *EvaluateExpr_Request) GetExprRange() *Range {
	if x != nil {
		return x.ExprRange
	}
	return nil
}

func (x *EvaluateExpr_Request) GetType() []byte {
	if x != nil {
		return x.Type
	}
	return nil
}

type EvaluateExpr_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value []byte `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *EvaluateExpr_Response) Reset() {
	*x = EvaluateExpr_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EvaluateExpr_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateExpr_Response) ProtoMessage() {}

func (x *EvaluateExpr_Response) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateExpr_Response.ProtoReflect.Descriptor instead.
func (*EvaluateExpr_Response) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{11, 1}
}

func (x *EvaluateExpr_Response) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type EmitIssue_Rule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Enabled  bool               `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Severity EmitIssue_Severity `protobuf:"varint,3,opt,name=severity,proto3,enum=proto.EmitIssue_Severity" json:"severity,omitempty"`
	Link     string             `protobuf:"bytes,4,opt,name=link,proto3" json:"link,omitempty"`
}

func (x *EmitIssue_Rule) Reset() {
	*x = EmitIssue_Rule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[37]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmitIssue_Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitIssue_Rule) ProtoMessage() {}

func (x *EmitIssue_Rule) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[37]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitIssue_Rule.ProtoReflect.Descriptor instead.
func (*EmitIssue_Rule) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{12, 0}
}

func (x *EmitIssue_Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmitIssue_Rule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *EmitIssue_Rule) GetSeverity() EmitIssue_Severity {
	if x != nil {
		return x.Severity
	}
	return EmitIssue_ERROR
}

func (x *EmitIssue_Rule) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type EmitIssue_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rule    *EmitIssue_Rule `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	Message string          `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Range   *Range          `protobuf:"bytes,3,opt,name=range,proto3" json:"range,omitempty"`
}

func (x *EmitIssue_Request) Reset() {
	*x = EmitIssue_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[38]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmitIssue_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitIssue_Request) ProtoMessage() {}

func (x *EmitIssue_Request) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[38]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitIssue_Request.ProtoReflect.Descriptor instead.
func (*EmitIssue_Request) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{12, 1}
}

func (x *EmitIssue_Request) GetRule() *EmitIssue_Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *EmitIssue_Request) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EmitIssue_Request) GetRange() *Range {
	if x != nil {
		return x.Range
	}
	return nil
}

type EmitIssue_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmitIssue_Response) Reset() {
	*x = EmitIssue_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_interface_proto_msgTypes[39]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmitIssue_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitIssue_Response) ProtoMessage() {}

func (x *EmitIssue_Response) ProtoReflect() protoreflect.Message {
	mi := &file_interface_proto_msgTypes[39]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitIssue_Response.ProtoReflect.Descriptor instead.
func (*EmitIssue_Response) Descriptor() ([]byte, []int) {
	return file_interface_proto_rawDescGZIP(), []int{12, 2}
}

var File_interface_proto protoreflect.FileDescriptor

var file_interface_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x38, 0x0a, 0x0b, 0x52, 0x75, 0x6c, 0x65,
	0x53, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x41, 0x0a, 0x0e, 0x52, 0x75, 0x6c, 0x65, 0x53, 0x65, 0x74, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x38, 0x0a, 0x09, 0x52, 0x75, 0x6c, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x22,
	0x4c, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x1a,
	0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x31, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x64,
	0x79, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x4c, 0x0a,
	0x0b, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x1a, 0x31, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f,
	0x64, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x1a,
	0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x36, 0x0a, 0x05, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x1a, 0x21, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x72, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x80, 0x02, 0x0a, 0x0a, 0x42, 0x6f, 0x64, 0x79, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x12, 0x3b, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42,
	0x6f, 0x64, 0x79, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x52, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12,
	0x2f, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x53, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73,
	0x1a, 0x1f, 0x0a, 0x09, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x1a, 0x63, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x12,
	0x25, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0xb7, 0x05, 0x0a, 0x0b, 0x42, 0x6f, 0x64, 0x79, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x42, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a,
	0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x06, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x3a, 0x0a, 0x12,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x72, 0x61, 0x6e,
	0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x10, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x1a, 0xb1, 0x01, 0x0a, 0x09, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x78,
	0x70, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x65, 0x78, 0x70, 0x72, 0x12, 0x22,
	0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x05, 0x72, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x2b, 0x0a, 0x0a, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12,
	0x2b, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x09, 0x65, 0x78, 0x70, 0x72, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x1a, 0xe4, 0x01, 0x0a,
	0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x73, 0x12, 0x26, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x29, 0x0a, 0x09, 0x64, 0x65,
	0x66, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x08, 0x64, 0x65, 0x66,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x0a, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x72, 0x61,
	0x6e, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x09, 0x74, 0x79, 0x70, 0x65, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x2f, 0x0a, 0x0c, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x5f, 0x72, 0x61, 0x6e, 0x67,
	0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x0b, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x73, 0x1a, 0x5b, 0x0a, 0x0f, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x32, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x42, 0x6f, 0x64, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x41, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0xb6, 0x01, 0x0a, 0x05, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x61,
	0x6e, 0x67, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x22,
	0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x52, 0x03, 0x65,
	0x6e, 0x64, 0x1a, 0x45, 0x0a, 0x03, 0x50, 0x6f, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x79, 0x74, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x62, 0x79, 0x74, 0x65, 0x22, 0x9d, 0x01, 0x0a, 0x0f, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x1a, 0x50, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x64,
	0x79, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x1a,
	0x38, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x45, 0x0a, 0x04, 0x46, 0x69, 0x6c,
	0x65, 0x1a, 0x1d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x1a, 0x1e, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x66, 0x69, 0x6c, 0x65,
	0x22, 0x90, 0x01, 0x0a, 0x0c, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x45, 0x78, 0x70,
	0x72, 0x1a, 0x5e, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x65, 0x78, 0x70, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x65, 0x78, 0x70, 0x72,
	0x12, 0x2b, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x5f, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x52, 0x09, 0x65, 0x78, 0x70, 0x72, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x1a, 0x20, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0xbc, 0x02, 0x0a, 0x09, 0x45, 0x6d, 0x69, 0x74, 0x49, 0x73, 0x73, 0x75,
	0x65, 0x1a, 0x7f, 0x0a, 0x04, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x35, 0x0a, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72,
	0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x45, 0x6d, 0x69, 0x74, 0x49, 0x73, 0x73, 0x75, 0x65, 0x2e, 0x53, 0x65, 0x76, 0x65,
	0x72, 0x69, 0x74, 0x79, 0x52, 0x08, 0x73, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x69,
	0x6e, 0x6b, 0x1a, 0x72, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a,
	0x04, 0x72, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x69, 0x74, 0x49, 0x73, 0x73, 0x75, 0x65, 0x2e, 0x52, 0x75,
	0x6c, 0x65, 0x52, 0x04, 0x72, 0x75, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x52,
	0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x1a, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x2e, 0x0a, 0x08, 0x53, 0x65, 0x76, 0x65, 0x72, 0x69, 0x74, 0x79, 0x12, 0x09,
	0x0a, 0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x41, 0x52,
	0x4e, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x4f, 0x54, 0x49, 0x43, 0x45,
	0x10, 0x02, 0x32, 0xad, 0x03, 0x0a, 0x07, 0x52, 0x75, 0x6c, 0x65, 0x53, 0x65, 0x74, 0x12, 0x46,
	0x0a, 0x0b, 0x52, 0x75, 0x6c, 0x65, 0x53, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x53, 0x65, 0x74, 0x4e, 0x61, 0x6d,
	0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x53, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0e, 0x52, 0x75, 0x6c, 0x65, 0x53, 0x65,
	0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x52, 0x75, 0x6c, 0x65, 0x53, 0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x52, 0x75, 0x6c, 0x65, 0x53, 0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x40, 0x0a, 0x09, 0x52, 0x75, 0x6c, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x73, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x75, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x73,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x70, 0x70, 0x6c,
	0x79, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x79, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x05,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0x9c, 0x02, 0x0a, 0x06, 0x52, 0x75, 0x6e, 0x6e, 0x65, 0x72, 0x12, 0x52, 0x0a,
	0x0f, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x12, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x31, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65,
	0x45, 0x78, 0x70, 0x72, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x76, 0x61,
	0x6c, 0x75, 0x61, 0x74, 0x65, 0x45, 0x78, 0x70, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x76, 0x61, 0x6c, 0x75, 0x61,
	0x74, 0x65, 0x45, 0x78, 0x70, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x40, 0x0a, 0x09, 0x45, 0x6d, 0x69, 0x74, 0x49, 0x73, 0x73, 0x75, 0x65, 0x12, 0x18, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x6d, 0x69, 0x74, 0x49, 0x73, 0x73, 0x75, 0x65, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x45,
	0x6d, 0x69, 0x74, 0x49, 0x73, 0x73, 0x75, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x74, 0x65, 0x72, 0x72, 0x61, 0x66, 0x6f, 0x72, 0x6d, 0x2d, 0x6c, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x73, 0x2f, 0x74, 0x66, 0x6c, 0x69, 0x6e, 0x74, 0x2d, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2d,
	0x73, 0x64, 0x6b, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_interface_proto_rawDescOnce sync.Once
	file_interface_proto_rawDescData = file_interface_proto_rawDesc
)

func file_interface_proto_rawDescGZIP() []byte {
	file_interface_proto_rawDescOnce.Do(func() {
		file_interface_proto_rawDescData = protoimpl.X.CompressGZIP(file_interface_proto_rawDescData)
	})
	return file_interface_proto_rawDescData
}

var file_interface_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_interface_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_interface_proto_goTypes = []interface{}{
	(EmitIssue_Severity)(0),          // 0: proto.EmitIssue.Severity
	(*RuleSetName)(nil),              // 1: proto.RuleSetName
	(*RuleSetVersion)(nil),           // 2: proto.RuleSetVersion
	(*RuleNames)(nil),                // 3: proto.RuleNames
	(*ConfigSchema)(nil),             // 4: proto.ConfigSchema
	(*ApplyConfig)(nil),              // 5: proto.ApplyConfig
	(*Check)(nil),                    // 6: proto.Check
	(*BodySchema)(nil),               // 7: proto.BodySchema
	(*BodyContent)(nil),              // 8: proto.BodyContent
	(*Range)(nil),                    // 9: proto.Range
	(*ResourceContent)(nil),          // 10: proto.ResourceContent
	(*File)(nil),                     // 11: proto.File
	(*EvaluateExpr)(nil),             // 12: proto.EvaluateExpr
	(*EmitIssue)(nil),                // 13: proto.EmitIssue
	(*RuleSetName_Request)(nil),      // 14: proto.RuleSetName.Request
	(*RuleSetName_Response)(nil),     // 15: proto.RuleSetName.Response
	(*RuleSetVersion_Request)(nil),   // 16: proto.RuleSetVersion.Request
	(*RuleSetVersion_Response)(nil),  // 17: proto.RuleSetVersion.Response
	(*RuleNames_Request)(nil),        // 18: proto.RuleNames.Request
	(*RuleNames_Response)(nil),       // 19: proto.RuleNames.Response
	(*ConfigSchema_Request)(nil),     // 20: proto.ConfigSchema.Request
	(*ConfigSchema_Response)(nil),    // 21: proto.ConfigSchema.Response
	(*ApplyConfig_Request)(nil),      // 22: proto.ApplyConfig.Request
	(*ApplyConfig_Response)(nil),     // 23: proto.ApplyConfig.Response
	(*Check_Request)(nil),            // 24: proto.Check.Request
	(*Check_Response)(nil),           // 25: proto.Check.Response
	(*BodySchema_Attribute)(nil),     // 26: proto.BodySchema.Attribute
	(*BodySchema_Block)(nil),         // 27: proto.BodySchema.Block
	(*BodyContent_Attribute)(nil),    // 28: proto.BodyContent.Attribute
	(*BodyContent_Block)(nil),        // 29: proto.BodyContent.Block
	nil,                              // 30: proto.BodyContent.AttributesEntry
	(*Range_Pos)(nil),                // 31: proto.Range.Pos
	(*ResourceContent_Request)(nil),  // 32: proto.ResourceContent.Request
	(*ResourceContent_Response)(nil), // 33: proto.ResourceContent.Response
	(*File_Request)(nil),             // 34: proto.File.Request
	(*File_Response)(nil),            // 35: proto.File.Response
	(*EvaluateExpr_Request)(nil),     // 36: proto.EvaluateExpr.Request
	(*EvaluateExpr_Response)(nil),    // 37: proto.EvaluateExpr.Response
	(*EmitIssue_Rule)(nil),           // 38: proto.EmitIssue.Rule
	(*EmitIssue_Request)(nil),        // 39: proto.EmitIssue.Request
	(*EmitIssue_Response)(nil),       // 40: proto.EmitIssue.Response
}
var file_interface_proto_depIdxs = []int32{
	26, // 0: proto.BodySchema.attributes:type_name -> proto.BodySchema.Attribute
	27, // 1: proto.BodySchema.blocks:type_name -> proto.BodySchema.Block
	30, // 2: proto.BodyContent.attributes:type_name -> proto.BodyContent.AttributesEntry
	29, // 3: proto.BodyContent.blocks:type_name -> proto.BodyContent.Block
	9,  // 4: proto.BodyContent.missing_item_range:type_name -> proto.Range
	31, // 5: proto.Range.start:type_name -> proto.Range.Pos
	31, // 6: proto.Range.end:type_name -> proto.Range.Pos
	7,  // 7: proto.ConfigSchema.Response.body:type_name -> proto.BodySchema
	8,  // 8: proto.ApplyConfig.Request.body:type_name -> proto.BodyContent
	7,  // 9: proto.BodySchema.Block.body:type_name -> proto.BodySchema
	9,  // 10: proto.BodyContent.Attribute.range:type_name -> proto.Range
	9,  // 11: proto.BodyContent.Attribute.name_range:type_name -> proto.Range
	9,  // 12: proto.BodyContent.Attribute.expr_range:type_name -> proto.Range
	8,  // 13: proto.BodyContent.Block.body:type_name -> proto.BodyContent
	9,  // 14: proto.BodyContent.Block.def_range:type_name -> proto.Range
	9,  // 15: proto.BodyContent.Block.type_range:type_name -> proto.Range
	9,  // 16: proto.BodyContent.Block.label_ranges:type_name -> proto.Range
	28, // 17: proto.BodyContent.AttributesEntry.value:type_name -> proto.BodyContent.Attribute
	7,  // 18: proto.ResourceContent.Request.schema:type_name -> proto.BodySchema
	8,  // 19: proto.ResourceContent.Response.content:type_name -> proto.BodyContent
	9,  // 20: proto.EvaluateExpr.Request.expr_range:type_name -> proto.Range
	0,  // 21: proto.EmitIssue.Rule.severity:type_name -> proto.EmitIssue.Severity
	38, // 22: proto.EmitIssue.Request.rule:type_name -> proto.EmitIssue.Rule
	9,  // 23: proto.EmitIssue.Request.range:type_name -> proto.Range
	14, // 24: proto.RuleSet.RuleSetName:input_type -> proto.RuleSetName.Request
	16, // 25: proto.RuleSet.RuleSetVersion:input_type -> proto.RuleSetVersion.Request
	18, // 26: proto.RuleSet.RuleNames:input_type -> proto.RuleNames.Request
	20, // 27: proto.RuleSet.ConfigSchema:input_type -> proto.ConfigSchema.Request
	22, // 28: proto.RuleSet.ApplyConfig:input_type -> proto.ApplyConfig.Request
	24, // 29: proto.RuleSet.Check:input_type -> proto.Check.Request
	32, // 30: proto.Runner.ResourceContent:input_type -> proto.ResourceContent.Request
	34, // 31: proto.Runner.File:input_type -> proto.File.Request
	36, // 32: proto.Runner.EvaluateExpr:input_type -> proto.EvaluateExpr.Request
	39, // 33: proto.Runner.EmitIssue:input_type -> proto.EmitIssue.Request
	15, // 34: proto.RuleSet.RuleSetName:output_type -> proto.RuleSetName.Response
	17, // 35: proto.RuleSet.RuleSetVersion:output_type -> proto.RuleSetVersion.Response
	19, // 36: proto.RuleSet.RuleNames:output_type -> proto.RuleNames.Response
	21, // 37: proto.RuleSet.ConfigSchema:output_type -> proto.ConfigSchema.Response
	23, // 38: proto.RuleSet.ApplyConfig:output_type -> proto.ApplyConfig.Response
	25, // 39: proto.RuleSet.Check:output_type -> proto.Check.Response
	33, // 40: proto.Runner.ResourceContent:output_type -> proto.ResourceContent.Response
	35, // 41: proto.Runner.File:output_type -> proto.File.Response
	37, // 42: proto.Runner.EvaluateExpr:output_type -> proto.EvaluateExpr.Response
	40, // 43: proto.Runner.EmitIssue:output_type -> proto.EmitIssue.Response
	34, // [34:44] is the sub-list for method output_type
	24, // [24:34] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_interface_proto_init() }
func file_interface_proto_init() {
	if File_interface_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_interface_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleSetName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleSetVersion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleNames); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigSchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Check); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BodySchema); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BodyContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Range); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluateExpr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmitIssue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleSetName_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleSetName_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleSetVersion_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleSetVersion_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleNames_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuleNames_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigSchema_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfigSchema_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyConfig_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplyConfig_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Check_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Check_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BodySchema_Attribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BodySchema_Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BodyContent_Attribute); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BodyContent_Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Range_Pos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceContent_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceContent_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluateExpr_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EvaluateExpr_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[37].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmitIssue_Rule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[38].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmitIssue_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_interface_proto_msgTypes[39].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmitIssue_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_interface_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_interface_proto_goTypes,
		DependencyIndexes: file_interface_proto_depIdxs,
		EnumInfos:         file_interface_proto_enumTypes,
		MessageInfos:      file_interface_proto_msgTypes,
	}.Build()
	File_interface_proto = out.File
	file_interface_proto_rawDesc = nil
	file_interface_proto_goTypes = nil
	file_interface_proto_depIdxs = nil
}
